version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: autocompany
      POSTGRES_PASS: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data
  autocompany:
    build:
      context: .
    ports:
      - "8090:8090"
    volumes:
      - ./autocompany:/autocompany
    command: python manage.py runserver 0.0.0.0:8090
    depends_on:
      - db
volumes:
  pgdata: