# Generated by Django 4.0.3 on 2022-08-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('license_no', models.CharField(max_length=250)),
                ('no_of_wheels', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreservice.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordererd_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('ordererd', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='coreservice.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreservice.user')),
            ],
        ),
    ]
