# Generated by Django 4.0.3 on 2022-08-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='vehicles',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='vehicle',
        ),
    ]
