# Generated by Django 4.0.3 on 2022-08-22 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreservice', '0002_rename_products_order_vehicles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'ordererd_date'},
        ),
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='vehicles',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
