# Generated by Django 4.0.3 on 2022-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreservice', '0005_alter_order_id_alter_orderitem_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
